region           = "ap-south-1"
alertSqsQueueURL = "https://sqs.ap-south-1.amazonaws.com/xxx/sqs-final-trigger-queue-to-application"
stageOneBucket = "op-a1-bucket-s3"
stageTwoBucket = "op-b1-bucket-s3"
stageThreeBucket = "op-abc1-bucket-s3"
