variable "region" {}
variable "alertSqsQueueURL" {}
variable "stageOneBucket" {}
variable "stageTwoBucket" {}
variable "stageThreeBucket" {}
variable "successBucket" {}
variable "failureBucket" {}
variable "logBucket" {}
variable "apigateway" {}
variable "stageOneSns" {}
variable "stageTwoSns" {}
variable "stageThreeSns" {}
variable "stageOneSqs" {}
variable "stageTwoSqs" {}
variable "stageThreeSqs" {}
variable "stageOneLambdaOne" {}
variable "stageOneLambdaTwo" {}
variable "stageTwoLambdaOne" {}
variable "stageTwoLambdaTwo" {}
variable "stageThreeLambdaOne" {}
variable "stageThreeLambdaTwo" {}
