#accessKey     = ""
#secretKey     = ""
region         = "eu-west-1"
lambdaname     = "lambda-aws-budget-action"
budgetName    = "JINOBUDGETS"
tagName       = "office-hours"
tagValue      = "ec-data-platform"