# accessKey           =""
# secretKey           =""
region              ="eu-west-1"
lambdaname          ="lambda-aws-ec2-stop"
tagName             ="office-hours"
tagValue            ="ec-data-platform"
